import { render, screen } from '@toptal/picasso/test-utils'
import React, { ComponentProps } from 'react'
import { RouteContext } from '@staff-portal/navigation'
import { ContractKind } from '@staff-portal/graphql/staff'
import {
  DeleteContractButton,
  ResendContractButton,
  VerifyContractButton
} from '@staff-portal/contracts'

import ContractItem from './ContractItem'
import { createContractFragmentMock } from '../../data/contract-fragment/mocks'

jest.mock('@staff-portal/contracts', () => ({
  DeleteContractButton: jest.fn(),
  ResendContractButton: jest.fn(),
  VerifyContractButton: jest.fn()
}))

const DeleteContractButtonMock = DeleteContractButton as jest.Mock
const ResendContractButtonMock = ResendContractButton as jest.Mock
const VerifyContractButtonMock = VerifyContractButton as jest.Mock

const renderComponent = (
  props: Omit<ComponentProps<typeof ContractItem>, 'clientId'>
) => {
  render(
    <RouteContext.Provider value={path => ({ url: path })}>
      <ContractItem {...props} clientId='clientId' />
    </RouteContext.Provider>
  )
}

describe('ContractItem', () => {
  const sharedLabels = [
    'Company',
    'Sender',
    'Sent At',
    'Type',
    'Status',
    'Signature Received At'
  ]

  const staLabels = [...sharedLabels, 'Last Resent At', 'Times Resent']

  const topLabels = [...sharedLabels, 'Job', 'Talent']

  beforeEach(() => {
    VerifyContractButtonMock.mockImplementation(() => <div />)
    ResendContractButtonMock.mockImplementation(() => <div />)
    DeleteContractButtonMock.mockImplementation(() => <div />)
  })

  describe('with STA contract', () => {
    const contract = createContractFragmentMock({ kind: ContractKind.STA })

    it('renders correct STA labels and values', () => {
      renderComponent({ contract })

      let allLabelsAndValues = ':'

      staLabels.forEach(label => {
        const field = screen.getByTestId(`item-field: ${label}`)

        expect(field).toBeInTheDocument()

        allLabelsAndValues += field.textContent + ':'
      })

      expect(allLabelsAndValues).toMatchInlineSnapshot(
        `":CompanyReceiver Company:SenderThe Undertaker:Sent At2020-03-11T09:49:20+0000:TypeSTA:StatusCreated:Signature Received At2020-05-11T09:49:20+0000:Last Resent At2020-04-11T09:49:20+0000:Times Resent3:"`
      )
    })

    it('renders label "Type" with "Clickable Contract" if there is no guid present', () => {
      renderComponent({ contract: { ...contract, guid: null } })

      const field = screen.getByTestId('item-field: Type')

      expect(field.textContent).toBe('TypeClickable Contract')
    })
  })

  describe('with TOP contract', () => {
    const contract = createContractFragmentMock()

    it('renders correct labels and values', () => {
      renderComponent({ contract })

      let allLabelsAndValues = ':'

      topLabels.forEach(label => {
        const field = screen.getByTestId(`item-field: ${label}`)

        expect(field).toBeInTheDocument()

        allLabelsAndValues += field.textContent + ':'
      })

      expect(allLabelsAndValues).toMatchInlineSnapshot(
        `":CompanyReceiver Company:SenderThe Undertaker:Sent At2020-03-11T09:49:20+0000:TypeTOP:StatusCreated:Signature Received At2020-05-11T09:49:20+0000:JobCEO:TalentAl Bundy:"`
      )
    })

    it('renders and links contract name', () => {
      renderComponent({ contract })

      const contractLink = screen.getByText('Incredible Contract')

      expect(contractLink).toBeInTheDocument()
      expect(contractLink.closest('a')?.href).toBe('http://click.here.com/')
    })

    it('renders and links talent name', () => {
      renderComponent({ contract })

      const talentLink = screen.getByText('Al Bundy')

      expect(talentLink).toBeInTheDocument()
      expect(talentLink.closest('a')?.href).toBe('http://al.bundy.com/')
    })

    it('renders and links job title', () => {
      renderComponent({ contract })

      const jobLink = screen.getByText('CEO')

      expect(jobLink).toBeInTheDocument()
      expect(jobLink.closest('a')?.href).toBe('http://funny.startup.com/')
    })

    it('renders auto-generated label', () => {
      renderComponent({
        contract: {
          ...contract,
          sender: {
            id: '123',
            fullName: 'TestName'
          },
          autoGenerated: true
        }
      })

      const senderNameField = screen.getByText('TestName (Automated)')

      expect(senderNameField).toBeInTheDocument()
    })

    describe('Operations', () => {
      it('adds VerifyContractAction and passes props correctly', () => {
        const onMutationSuccess = () => {}

        renderComponent({ contract, onMutationSuccess })

        const expectedProps: ComponentProps<typeof VerifyContractButton> = {
          contractId: contract.id,
          operation: contract.operations.verifyContract,
          onMutationSuccess,
          hasLongLabel: true
        }

        expect(VerifyContractButtonMock).toHaveBeenCalledWith(
          expectedProps,
          expect.anything()
        )
      })
    })

    it('adds ResendContractButton and passes props correctly', () => {
      const onMutationSuccess = () => {}

      renderComponent({ contract, onMutationSuccess })

      const expectedProps: ComponentProps<typeof ResendContractButton> = {
        contractId: contract.id,
        operation: contract.operations.resendContract,
        onMutationSuccess,
        hasLongLabel: true
      }

      expect(ResendContractButtonMock).toHaveBeenCalledWith(
        expectedProps,
        expect.anything()
      )
    })

    it('adds DeleteContractButton and passes props correctly', () => {
      const onMutationSuccess = () => {}

      renderComponent({ contract, onMutationSuccess })

      const expectedProps: ComponentProps<typeof DeleteContractButton> = {
        contractId: contract.id,
        contractKind: contract.kind,
        contractStatus: contract.status,
        contractWebResource: contract.webResource,
        operation: contract.operations.destroyContract,
        onMutationSuccess: expect.any(Function)
      }

      expect(DeleteContractButtonMock).toHaveBeenCalledWith(
        expectedProps,
        expect.anything()
      )
    })
  })
})
