import React from 'react'
import {
  DetailedList,
  LinkWrapper,
  SubSection,
  WebResourceLink
} from '@staff-portal/ui'
import { Typography, TypographyOverflow } from '@toptal/picasso'
import { useMessageEmitter } from '@toptal/staff-portal-message-bus'
import { useUserDateFormatter } from '@staff-portal/current-user'
import { ContractStatusField } from '@staff-portal/talents'
import { CLIENT_UPDATED } from '@staff-portal/clients'
import { NO_VALUE } from '@staff-portal/config'
import {
  DeleteContractButton,
  ResendContractButton,
  VerifyContractButton
} from '@staff-portal/contracts'

import { ContractFragment } from '../../data/contract-fragment'

export type Props = {
  clientId: string
  contract: ContractFragment
  last?: boolean
  onMutationSuccess?: () => void
}

// eslint-disable-next-line complexity
const ContractItem = ({
  clientId,
  contract,
  last,
  onMutationSuccess
}: Props) => {
  const emitMessage = useMessageEmitter()
  const userDateFormatter = useUserDateFormatter()

  const onDestroyContract = () => {
    onMutationSuccess?.()
    emitMessage(CLIENT_UPDATED, { companyId: clientId })
  }

  const {
    guid,
    kind,
    status,
    autoGenerated,
    signatureReceivedAt,
    resentCount,
    subject,
    receiver,
    sender,
    sentAt,
    resentAt,
    id,
    webResource,
    operations: { destroyContract, resendContract, verifyContract }
  } = contract

  const senderNameLabel = autoGenerated
    ? `${sender?.fullName} (Automated)`
    : sender?.fullName

  const isSTA = kind === 'STA'

  return (
    <SubSection
      title={
        <LinkWrapper
          wrapWhen={Boolean(webResource.url)}
          href={webResource.url as string}
        >
          <TypographyOverflow
            as='span'
            weight='inherit'
            size='inherit'
            color='inherit'
          >
            {webResource.text}
          </TypographyOverflow>
        </LinkWrapper>
      }
      last={last}
      actions={
        <>
          <VerifyContractButton
            contractId={id}
            operation={verifyContract}
            onMutationSuccess={onMutationSuccess}
            hasLongLabel
          />

          <ResendContractButton
            contractId={id}
            operation={resendContract}
            onMutationSuccess={onMutationSuccess}
            hasLongLabel
          />

          <DeleteContractButton
            contractId={id}
            contractKind={kind}
            contractStatus={status}
            contractWebResource={webResource}
            operation={destroyContract}
            onMutationSuccess={onDestroyContract}
          />
        </>
      }
    >
      <DetailedList defaultValue={NO_VALUE} labelColumnWidth={11}>
        <DetailedList.Row>
          <DetailedList.Item label='Company' value={receiver?.fullName} />
          <DetailedList.Item
            label='Type'
            // STAs without guid are always clickable contracts
            value={isSTA && !guid ? 'Clickable Contract' : kind}
          />
        </DetailedList.Row>
        <DetailedList.Row>
          <DetailedList.Item label='Sender' value={senderNameLabel} />
          <DetailedList.Item label='Status'>
            {status && <ContractStatusField status={status} />}
          </DetailedList.Item>
        </DetailedList.Row>
        <DetailedList.Row>
          <DetailedList.Item
            label='Sent At'
            value={sentAt && userDateFormatter(sentAt)}
          />
          <DetailedList.Item
            label='Signature Received At'
            value={
              signatureReceivedAt && userDateFormatter(signatureReceivedAt)
            }
          />
        </DetailedList.Row>
        <DetailedList.Row>
          <DetailedList.Item label={isSTA ? 'Last Resent At' : 'Job'}>
            {isSTA
              ? resentAt && userDateFormatter(resentAt)
              : subject?.job && (
                  <Typography size='medium'>
                    <WebResourceLink link={subject.job.webResource} />
                  </Typography>
                )}
          </DetailedList.Item>
          <DetailedList.Item label={isSTA ? 'Times Resent' : 'Talent'}>
            {isSTA
              ? String(resentCount)
              : subject?.talent && (
                  <Typography size='medium'>
                    <WebResourceLink link={subject.talent.webResource} />
                  </Typography>
                )}
          </DetailedList.Item>
        </DetailedList.Row>
      </DetailedList>
    </SubSection>
  )
}

export default ContractItem
