export enum GraphQLErrorCode {
  INVALID_ARGUMENT = 'INVALID_ARGUMENT',
  INVALID_ARGUMENT_SYNTAX = 'INVALID_ARGUMENT_SYNTAX',
  TOS_UNACCEPTED = 'TOS_UNACCEPTED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  UNAUTHORIZED_PORTAL = 'UNAUTHORIZED_PORTAL',
  UNAUTHORIZED = 'UNAUTHORIZED',
  EMPTY = 'EMPTY',
  THIRD_PARTY_SERVICE_ERROR = 'THIRD_PARTY_SERVICE_ERROR',
  UPLOAD_LIMIT_EXCEEDED = 'UPLOAD_LIMIT_EXCEEDED'
}
