import processEmailBody from './process-email-body'

describe('processEmailBody', () => {
  it('processes email body with project brief tokens removed', () => {
    const BODY_WITHOUT_PROJECT_BRIEF =
      "Hi Patrick,\r\n\r\nIt was great speaking to you earlier. Congratulations on passing this part of the Toptal developer screening process.\r\n\r\nThe second developer interview evaluates your skills via a take-home project. You will find the project requirements in this email. Please treat this project as if you are delivering it to a client.\r\n\r\nHelpful take-home project guidelines:\r\n\r\n• This project will be used to evaluate your skills and should be fully functional without any obvious missing pieces. We will evaluate the project as if you were delivering it to a customer.\r\n• The deadline to submit your completed project is 2 weeks from the date you received the project requirements.\r\n• If you schedule your final interview after the 2-week deadline, make sure to submit your completed project and all code to the private repository before the deadline. Everything that is submitted after the deadline will not be taken into consideration.\r\n• Please do not commit any code at least 12 hours before the meeting time so that it can be reviewed. Anything that is submitted after this time will not be taken into consideration.\r\n• Please join the meeting room for this final interview on time. If you miss your interview without providing any prior notice, your application may be paused for six months.\r\n\r\nPlease [schedule an interview time]({{ booking_url }}) that is most suitable for you. Bear in mind that you will need to show a finished project during this interview. \r\n\r\nOnce you pick an appointment time, we'll email you with additional meeting details and the contact details of another senior developer from our team who will assess your project and conduct your next interview. **They are acting as your client for this project and are your point of contact for any questions you may have during the development of this project.** \r\n\r\nThanks,\r\n{{sender.first_name}}\n\n{{sender.signature}}"

    expect(processEmailBody(BODY_WITHOUT_PROJECT_BRIEF)).toStrictEqual({
      emailBody: BODY_WITHOUT_PROJECT_BRIEF
    })

    const BODY_WITH_PROJECT_BRIEF =
      "Hi Patrick,\r\n\r\nIt was great speaking to you earlier. Congratulations on passing this part of the Toptal developer screening process.\r\n\r\nThe second developer interview evaluates your skills via a take-home project. You will find the project requirements in this email. Please treat this project as if you are delivering it to a client.\r\n\r\n\n\n--- PROJECT BRIEF START ---\n\r\n\r\nThe requirements for the test project are:\r\n<< PROJECT REQUIREMENTS >>\r\n\r\nPlease use this private repository to version-control your code:\r\n<< PROJECT REPO LINK >>\r\nUsername: << PROJECT REPO USERNAME >>\r\nPassword: << PROJECT REPO PASSWORD >>\r\n\r\n\n--- PROJECT BRIEF END ---\n\n\r\n\r\nHelpful take-home project guidelines:\r\n\r\n• This project will be used to evaluate your skills and should be fully functional without any obvious missing pieces. We will evaluate the project as if you were delivering it to a customer.\r\n• The deadline to submit your completed project is 2 weeks from the date you received the project requirements.\r\n• If you schedule your final interview after the 2-week deadline, make sure to submit your completed project and all code to the private repository before the deadline. Everything that is submitted after the deadline will not be taken into consideration.\r\n• Please do not commit any code at least 12 hours before the meeting time so that it can be reviewed. Anything that is submitted after this time will not be taken into consideration.\r\n• Please join the meeting room for this final interview on time. If you miss your interview without providing any prior notice, your application may be paused for six months.\r\n\r\nPlease [schedule an interview time]({{ booking_url }}) that is most suitable for you. Bear in mind that you will need to show a finished project during this interview. \r\n\r\nOnce you pick an appointment time, we'll email you with additional meeting details and the contact details of another senior developer from our team who will assess your project and conduct your next interview. **They are acting as your client for this project and are your point of contact for any questions you may have during the development of this project.** \r\n\r\nThanks,\r\n{{sender.first_name}}\n\n{{sender.signature}}"

    expect(processEmailBody(BODY_WITH_PROJECT_BRIEF)).toStrictEqual({
      emailBody:
        "Hi Patrick,\r\n\r\nIt was great speaking to you earlier. Congratulations on passing this part of the Toptal developer screening process.\r\n\r\nThe second developer interview evaluates your skills via a take-home project. You will find the project requirements in this email. Please treat this project as if you are delivering it to a client.\r\n\r\n\n\n\n\r\n\r\nThe requirements for the test project are:\r\n<< PROJECT REQUIREMENTS >>\r\n\r\nPlease use this private repository to version-control your code:\r\n<< PROJECT REPO LINK >>\r\nUsername: << PROJECT REPO USERNAME >>\r\nPassword: << PROJECT REPO PASSWORD >>\r\n\r\n\n\n\n\r\n\r\nHelpful take-home project guidelines:\r\n\r\n• This project will be used to evaluate your skills and should be fully functional without any obvious missing pieces. We will evaluate the project as if you were delivering it to a customer.\r\n• The deadline to submit your completed project is 2 weeks from the date you received the project requirements.\r\n• If you schedule your final interview after the 2-week deadline, make sure to submit your completed project and all code to the private repository before the deadline. Everything that is submitted after the deadline will not be taken into consideration.\r\n• Please do not commit any code at least 12 hours before the meeting time so that it can be reviewed. Anything that is submitted after this time will not be taken into consideration.\r\n• Please join the meeting room for this final interview on time. If you miss your interview without providing any prior notice, your application may be paused for six months.\r\n\r\nPlease [schedule an interview time]({{ booking_url }}) that is most suitable for you. Bear in mind that you will need to show a finished project during this interview. \r\n\r\nOnce you pick an appointment time, we'll email you with additional meeting details and the contact details of another senior developer from our team who will assess your project and conduct your next interview. **They are acting as your client for this project and are your point of contact for any questions you may have during the development of this project.** \r\n\r\nThanks,\r\n{{sender.first_name}}\n\n{{sender.signature}}",
      projectBrief:
        '\n\r\n\r\nThe requirements for the test project are:\r\n<< PROJECT REQUIREMENTS >>\r\n\r\nPlease use this private repository to version-control your code:\r\n<< PROJECT REPO LINK >>\r\nUsername: << PROJECT REPO USERNAME >>\r\nPassword: << PROJECT REPO PASSWORD >>\r\n\r\n\n'
    })
  })
})
