import React from 'react'
import { ContractKind, Link } from '@staff-portal/graphql/staff'
import { DetailedList as DL, LinkWrapper } from '@staff-portal/ui'
import { useUserDateFormatter } from '@staff-portal/current-user'
import { getTalentProfileLinkTarget } from '@staff-portal/jobs'
import { NO_VALUE } from '@staff-portal/config'
import { ContractStatusField, ContractTypeField } from '@staff-portal/talents'

import { JobContractFragment } from '../../data/get-job-contracts'
import { LABEL_COLUMN_EXPANDED_SECTION_WIDTH } from '../../../../../../config'

type Props = {
  contract: JobContractFragment
  jobWebResource: Link
}

const JobContractItemFields = ({ contract, jobWebResource }: Props) => {
  const {
    kind,
    status,
    sender,
    sentAt,
    signatureReceivedAt,
    subject,
    inheritedFrom,
    autoGenerated
  } = contract

  const userDateFormatter = useUserDateFormatter()
  const tooltip = inheritedFrom ? 'Inherited from parent company' : undefined

  const senderNameLabel = autoGenerated
    ? `${sender?.fullName} (Automated)`
    : sender?.fullName

  return (
    <DL
      labelColumnWidth={LABEL_COLUMN_EXPANDED_SECTION_WIDTH}
      defaultValue={NO_VALUE}
    >
      <DL.Row>
        <DL.Item label='Type'>
          {kind && <ContractTypeField kind={kind} tooltip={tooltip} />}
        </DL.Item>
      </DL.Row>

      <DL.Row>
        <DL.Item label='Sender' value={senderNameLabel} />
        <DL.Item label='Status'>
          {status && <ContractStatusField status={status} />}
        </DL.Item>
      </DL.Row>

      <DL.Row>
        <DL.Item label='Sent at' value={userDateFormatter(sentAt)} />
        <DL.Item
          label='Signature Received at'
          value={signatureReceivedAt && userDateFormatter(signatureReceivedAt)}
        />
      </DL.Row>

      <DL.Row>
        <DL.Item label='Job'>
          {kind && [ContractKind.STA, ContractKind.TOP].includes(kind) && (
            <LinkWrapper
              wrapWhen={Boolean(jobWebResource.url)}
              href={jobWebResource.url as string}
            >
              {jobWebResource.text}
            </LinkWrapper>
          )}
        </DL.Item>

        {subject?.talent && (
          <DL.Item label={subject.talent.type}>
            <LinkWrapper
              wrapWhen={Boolean(subject.talent.webResource.url)}
              href={subject.talent.webResource.url as string}
              target={getTalentProfileLinkTarget(
                subject.talent.webResource.url
              )}
            >
              {subject.talent.webResource.text}
            </LinkWrapper>
          </DL.Item>
        )}
      </DL.Row>
    </DL>
  )
}

export default JobContractItemFields
