export enum FilterConfigType {
  AMOUNT_RANGE = 'AMOUNT_RANGE',
  AUTOCOMPLETE = 'AUTOCOMPLETE',
  CHECKBOX = 'CHECKBOX',
  CITY = 'CITY',
  DATE_RANGE = 'DATE_RANGE',
  HIDDEN = 'HIDDEN',
  RADIO = 'RADIO',
  PRESET = 'PRESET',
  SELECT = 'SELECT',
  SLIDER_RANGE = 'SLIDER_RANGE',
  TAG_SELECTOR = 'TAG_SELECTOR',
  TYPE_SELECTOR = 'TYPE_SELECTOR'
}
