export { default as HighlightsTalentCardSection } from './HighlightsTalentCardSection'
export { default as IndustriesTalentCardSection } from './IndustriesTalentCardSection'
export { default as PortfolioTalentCardSection } from './PortfolioTalentCardSection'
export { default as SkillsTalentCardSection } from './SkillsTalentCardSection'
export { default as JobApplicationInfoSection } from './JobApplicationInfoSection'
export { default as JobApplicantTalentCardSkeletonLoader } from './JobApplicantTalentCardSkeletonLoader'
