// TODO: remove when GraphQL API will provide typed cumulative status for engagements
// See status docs: https://toptal-core.atlassian.net/wiki/spaces/GOLD/pages/2010350584/Engagement+Talent+Details#Status
export enum EngagementCumulativeStatus {
  DRAFT = 'draft',
  READY_TO_SEND = 'ready_to_send',
  PENDING = 'pending',
  PENDING_LEGAL = 'pending_legal',
  PENDING_APPROVAL = 'pending_approval',
  REJECTED_DRAFT = 'rejected_draft',
  UNSAVED_DRAFT = 'unsaved_draft',
  CANCELLED_DRAFT = 'cancelled_draft',
  SCHEDULED = 'scheduled',
  ON_TRIAL = 'on_trial',
  ON_HOLD = 'on_hold',
  ACTIVE = 'active',
  REJECTED_INTERVIEW = 'rejected_interview',
  CLOSED = 'closed',
  EXPIRED = 'expired',
  ON_BREAK = 'on_break',
  CANCELLED = 'cancelled',
  PENDING_EXPIRATION = 'pending_expiration',
  END_SCHEDULED = 'end_scheduled',
  REJECTED_TRIAL = 'rejected_trial',
  INTERVIEW_INTERNAL = 'interview_internal',
  INTERVIEW_PENDING = 'interview_pending',
  INTERVIEW_SCHEDULED = 'interview_scheduled',
  INTERVIEW_TIME_REJECTED = 'interview_time_rejected',
  INTERVIEW_TIME_ACCEPTED = 'interview_time_accepted',
  INTERVIEW_MISSED = 'interview_missed',
  INTERVIEW_ACCEPTED = 'interview_accepted',
  INTERVIEW_REJECTED = 'interview_rejected',
  INTERVIEW_EXPIRED = 'interview_expired',
  EXPIRATION_POSTPONED = 'expiration_postponed',
  INTERVIEW_OCCURRED = 'interview_occurred',
  INTERVIEW_NOT_OCCURRED = 'interview_not_occurred',
  INTERVIEW_OCCURRED_VERIFIED_BY_STAFF = 'interview_occurred_verified_by_staff',
  INTERVIEW_NOT_OCCURRED_VERIFIED_BY_STAFF = 'interview_not_occurred_verified_by_staff'
}
