export { default as AddVertical } from './AddVertical'
export { default as BasePage } from './BasePage'
export { default as CallRequestsPage } from './CallRequestsPage'
export { default as CallsPage } from './CallsPage'
export { CandidateSendingPage } from './candidate-sending'
export { default as CommunityLeadersPage } from './CommunityLeadersPage'
export { CompanyApplicants } from './companies'
export { default as MeetingsPage } from './MeetingsPage'
export { default as QuizzesPage } from './QuizzesPage'
export { default as SkillsPage } from './SkillsPage'
export { default as TalentCoachingPage } from './TalentCoachingPage'
export { default as EmailMessagesPage } from './EmailMessagesPage'
export { default as TalentListPage } from './TalentListPage'
export { default as TalentApplicantsPage } from './TalentApplicantsPage'
export * from './talents'
export { default as EmailTemplatesPage } from './EmailTemplatesPage'
