import {
  ContractKind,
  ContractStatus,
  OperationCallableTypes
} from '@staff-portal/graphql/staff'
import { encodeEntityId } from '@staff-portal/data-layer-service'

import { ContractFragment } from './contract-fragment.staff.gql.types'

export const createContractFragmentMock = (
  partialContract: Partial<ContractFragment> = {}
): ContractFragment => {
  const defaultContract = {
    id: encodeEntityId('123', 'Test'),
    guid: encodeEntityId('123', 'Test'),
    kind: ContractKind.TOP,
    status: ContractStatus.CREATED,
    sentAt: '2020-03-11T09:49:20+0000' as const,
    resentAt: '2020-04-11T09:49:20+0000' as const,
    resentCount: 3,
    autoGenerated: false,
    signatureReceivedAt: '2020-05-11T09:49:20+0000' as const,
    operations: {
      destroyContract: {
        callable: OperationCallableTypes.DISABLED,
        messages: [],
        __typename: 'Operation'
      },
      resendContract: {
        callable: OperationCallableTypes.ENABLED,
        messages: [],
        __typename: 'Operation'
      },
      verifyContract: {
        callable: OperationCallableTypes.HIDDEN,
        messages: [],
        __typename: 'Operation'
      }
    },
    receiver: {
      id: encodeEntityId('123', 'Test'),
      fullName: 'Receiver Company',
      __typename: 'Client'
    },
    sender: {
      id: encodeEntityId('123', 'Test'),
      fullName: 'The Undertaker',
      __typename: 'Staff'
    },
    webResource: {
      text: 'Incredible Contract',
      url: 'http://click.here.com/',
      __typename: 'Link'
    },
    subject: {
      id: encodeEntityId('123', 'Test'),
      talent: {
        id: encodeEntityId('123', 'Test'),
        webResource: {
          text: 'Al Bundy',
          url: 'http://al.bundy.com',
          __typename: 'Link'
        },
        __typename: 'Talent'
      },
      job: {
        id: encodeEntityId('123', 'Test'),
        webResource: {
          text: 'CEO',
          url: 'http://funny.startup.com/',
          __typename: 'Link'
        },
        __typename: 'Job'
      },
      __typename: 'Engagement'
    },
    __typename: 'Contract'
  }

  return {
    ...defaultContract,
    ...partialContract
  }
}
