export { default as SendEmailModal } from './SendEmailModal'
export { default as BasicModal } from './BasicModal'
export { default as FormModal } from './FormModal'
export { default as ChangeOfacStatusModal } from './ChangeOfacStatusModal'
export { default as DeleteApplicationModal } from './DeleteApplicationModal'
export { default as MarkAsBadLeadModal } from './MarkAsBadLeadModal'
export { default as CheckComplianceModal } from './CheckComplianceModal'
