export { TALENT_STATUS_MAPPING } from './talent-status-mapping'
export { TALENT_AVAILABILITY_COLOR_MAPPING } from './talent-availability-color-mapping'
export { TALENT_AVAILABILITY_STATUS_COMPACT_MAPPING } from './talent-availability-status-compact-mapping'
export { TALENT_AVAILABILITY_STATUS_MAPPING } from './talent-availability-status-mapping'
export { getTalentAvailabilityStatusSettings } from './get-talent-availability-status-settings/get-talent-availability-status-settings'
