import { gql } from '@staff-portal/data-layer-service'
import { OPERATION_FRAGMENT } from '@staff-portal/operations'
import { WEB_RESOURCE_FRAGMENT } from '@staff-portal/facilities'

export const CONTRACT_COMMON_FRAGMENT = gql`
  fragment ContractCommonFragment on Contract {
    id
    kind
    sentAt
    signatureReceivedAt
    autoGenerated
    status
    ...WebResourceFragment
    operations {
      destroyContract {
        ...OperationFragment
      }
      resendContract {
        ...OperationFragment
      }
      verifyContract {
        ...OperationFragment
      }
    }
  }
  ${OPERATION_FRAGMENT}
  ${WEB_RESOURCE_FRAGMENT}
`
